service: aws-node-typescript-api
frameworkVersion: '3'
plugins:
  - serverless-openapi-documenter
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin
  - serverless-plugin-ifelse
  - serverless-plugin-dynamodb-autoscaling
  - serverless-dynamodb-local
  - serverless-offline
useDotenv: true
configValidationMode: error
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  region: ${env:REGION}
  logs: ${file(serverless/provider/logs/logs.yml):logs}
package:
  individually: true
functions:
  createTodo: ${file(serverless/lambda/todos/create-todo.yml):createTodo}
resources:
  Resources:
    todoTable: ${file(serverless/resources/todos/todo-table.yml):todoTable}
custom:
  currentStage: ${opt:stage, self:provider.stage, 'local'}
  serverlessIfElse:
    - If: '"${self:custom.currentStage}" == "local"'
      Set:
        custom.dynamodb.start.host: ${env:DYNAMODB_HOST}
        custom.dynamodb.start.port: ${env:DYNAMODB_PORT}
  dynamodb: ${file(serverless/custom/dynamodb/dynamodb-local.yml):dynamodb}
  webpack: ${file(serverless/custom/webpack/webpack.yml):webpack}
  todoTable: 'todo-table-${sls:stage}'
  dynamodbAutoscaling:
    tablesConfig:
      # Disable autoscaling for all tables
      "*": false
      todoTable: ${file(serverless/custom/dynamodb-scaling/todos/todo-table.yml):todoTable}
  documentation: ${file(serverless/custom/documentation/documentation.yml):documentation}
