todoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${env:DYNAMODB_TABLE_TODO}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    KeySchema:
      - AttributeName: id
        KeyType: HASH
