todoTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${env:DYNAMODB_TABLE_TODO}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
      - AttributeName: updatedAt
        AttributeType: S
      - AttributeName: deletedAt
        AttributeType: S
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: createdAtIndexName
        KeySchema:
          - AttributeName: createdAt
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: updatedAtIndexName
        KeySchema:
          - AttributeName: updatedAt
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      - IndexName: deletedAtIndexName
        KeySchema:
          - AttributeName: deletedAt
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
